name: Create a new comment
on:
 issues:
  types: [opened]
jobs:
  comment_with-action:
   runs-on: ubuntu-latest
   steps:
    - name: "Github com"
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
    
