name: Create a new comment
on:
 issues:
  types: [opened]
jobs:
 comment_with-action:
   runs-on: ubuntu-latest
   steps:
    - name: "Github com"
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v4
      with: 
          issue-number: ${{ (github.event.issue.number) }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1' 
 comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with api
        run: 
          gh api --method POST /repos/mohamed-taoufik/myapp-migrate/issues \
          --header "Accept:application/vnd.github+json" \
          --header "X-GitHub-Api-Version:2022-11-28" \
          -f title='Created with the REST API' \
          -f body='This is a test issue created by the REST API' \
        shell: bash

        env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
         #ORGANIZATION: {{github.event.organisation.login}}
         #REPOSITORY: {{github.event.repository.name}}
         #ISSUE_NUMBER: {{github.event.issue.number}}
 comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "Hello, thanks for opening this issue!"
            })
          github-token: ${{secrets.GITHUB_TOKEN}}      
