name: mvnapp/mavenapp
on: [push] #workflow_dispatch
#   # The shortest interval you can run scheduled workflows is once every 5 minutes.
#   period: '180'
jobs:
  Default-Stage-Default-Job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        clean: false
    - uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '11'
    - name: Run Maven
      run: mvn clean package
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2.12.0
      if: always()
      with:
        junit_files: "**/target/surefire-reports/*.xml"
    - name: Upload jar file
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: /home/runner/work/myapp-migrate/myapp-migrate/target/myapp-1.0-SNAPSHOT.jar
    - name: Download jar file
      uses: actions/download-artifact@v2
      with:
        name: myapp
        path: jar/myapp.jar
    #- name: Run jar file
     # run: java -jar jar/myapp.jar
    - name: contents of your jar file
      run: jar tf jar/myapp.jar

